# Spring 数据源 (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #数据库连接驱动
    # url: jdbc:mysql://192.168.99.100:3306/jpa_practice_db?useSSL=false #数据库连接的url
    url: jdbc:mysql://localhost:3306/jpa_practice_db?useSSL=false #数据库连接的url
    username: root #用户名
    # password: 123456 #用户密码
    password: akigaze #用户密码

  jpa:
    hibernate:
      ddl-auto: create #每次启动应用都自动删除数据库中的表，在根据Entity的配置自动创建数据表
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # Hibernate 属性，SQL 方言使得 Hibernate 为所选数据库生成更好的 SQL
        show_sql: true #Enable the logging of all the generated SQL statements to the console
        format_sql: true #Format the generated SQL statement to make it more readable, but takes up more screen space.
        use_sql_comments: true #Hibernate will put comments inside all generated SQL statements to hint what’s the generated SQL trying to do
        generate_statistics: false #生成统计